################################################################
# Train on MusicLDM +OB+TB with multi-dataset (StemGMD + IDMT) #
################################################################

# 1. change train data path and validation data path
# 2. change the onset_loss_weight and timbre_loss_weight

id:
  name: "integrated_musicldm_timbre_0.5_onset_0.05"
  version: "v1.0"

mode: "train"

project_name: "integrated_musicldm_timbre_0.5_onset_0.05"
log_directory: "/home/ddmanddman/msgld_dssdt/lightning_logs"

data:
  target: src.utilities.data.datamodule.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 24
    
    augmentation:
      mixup: 0.0
      return_all_wav: False
      balanced_sampling: False
      masking: False
    
    path:
      dataset_type: "StemGMDOnset"
      train_data:
        - /home/ddmanddman/msgld_dssdt/data/StemGMD_org/train
        - /home/ddmanddman/msgld_dssdt/data/IDMT/train
        - /home/ddmanddman/msgld_dssdt/data/StemGMD_org/validation
      valid_data: /home/ddmanddman/msgld_dssdt/data/StemGMD_org/test
      label_data: null
      stems:
        - kick
        - snare
        - toms
        - hi_hats
        - cymbals
      shuffle_val_test: False
    
    preprocessing:
      audio:
        sampling_rate: 16000
        max_wav_value: 32768.0
      stft:
        filter_length: 1024
        hop_length: 160
        win_length: 1024
      mel:
        n_mel_channels: 64
        mel_fmin: 0
        mel_fmax: 8000
        freqm: 0
        timem: 0
        blur: False
        target_length: 1024

model:
  target: latent_diffusion.models.musicldm.MusicLDM_multitask
  params:
    num_stems: 5
    conditioning_key: concat
    concat_mode: true
    base_learning_rate: 3.0e-05
    batchsize: 45
    monitor: "val/loss"
    scale_by_std: True
    
    enable_onset_prediction: True
    enable_timbre_prediction: True
    onset_loss_weight: 0.05
    timbre_loss_weight: 0.5
    onset_warmup_steps: 2000
    onset_data_path: "/home/ddmanddman/msgld_dssdt/midi_onset_gt"
    track_mapping_path: "/home/ddmanddman/msgld_dssdt/track_mapping.csv"
    
    # Guide Features (Not used)
    enable_guide_features: False
    guide_features:
      F_med: 17
      T_med: 9
      p_mask: 2
      hf_threshold: 6000
      lf_threshold: 200
      guide_channels: 4
      latent_channels: 2
      film_dim: 32
    
    onset_data_path: "/home/ddmanddman/msgld_dssdt/midi_onset_gt"
    timbre_data_path: "/home/ddmanddman/msgld_dssdt/data/StemGMD_timbre"
    track_mapping_path: "/home/ddmanddman/msgld_dssdt/track_mapping.csv"
    
    timesteps: 1000
    beta_schedule: "linear"
    linear_start: 0.0015
    linear_end: 0.0195
    cosine_s: 8e-3
    parameterization: "eps"
    first_stage_key: fbank_stems
    cond_stage_key: fbank
    
    use_noise: True
    use_random_timesteps: True
    fixed_timestep: 0
    
    latent_t_size: 256
    latent_f_size: 16
    z_channels: 8
    channels: 5
    
    use_ema: True
    log_every_t: 100
    loss_type: "l2"
    
    first_stage_config:
      target: latent_encoder.autoencoder.AutoencoderKL
      params:
        reload_from_ckpt: "/home/ddmanddman/msgld_dssdt/vae-ckpt.ckpt"
        batchsize: 4
        monitor: "val/rec_loss"
        image_key: "fbank"
        subband: 1
        embed_dim: 8
        time_shuffle: 1
        mel_num: 64
        lossconfig:
          target: latent_diffusion.modules.losses.LPIPSWithDiscriminator
          params:
            disc_start: 50001
            kl_weight: 1.0
            disc_weight: 0.5
            disc_in_channels: 1
        ddconfig:
          double_z: True
          hifigan_ckpt: "/home/ddmanddman/msgld_dssdt/hifigan-ckpt.ckpt"
          z_channels: 8
          resolution: 256
          downsample_time: False
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
    
    unet_config:
      target: latent_diffusion.modules.diffusionmodules.openaimodel.UNetModel_with_multitask
      params:
        image_size: 64
        extra_film_use_concat: True
        in_channels: 5
        out_channels: 5
        model_channels: 128
        no_condition: False
        dims: 3
        attention_resolutions: [8, 4, 2]
        num_res_blocks: 2
        channel_mult: [1, 2, 3, 5]
        num_head_channels: 32
        use_spatial_transformer: False
        
        use_onset_branch: True
        use_timbre_branch: True
        onset_output_frames: 1024
        timbre_feature_dim: 7
        num_stems: 5
    
    cond_stage_config:
      target: latent_diffusion.modules.encoders.modules.Patch_Cond_Model
      params:
        sampling_rate: 16000
        embed_mode: "fbank"
        unconditional_prob: 0.0
    
    # Evaluation
    evaluation_params:
      ddim_sampling_steps: 200
      n_candidates_per_samples: 1
      unconditional_guidance_scale: 1.0

trainer:
  max_epochs: 100
  val_check_interval: 1.0
  save_checkpoint_every_n_steps: 500
  save_top_k: 2
  limit_train_batches: 1.0
  # limit_train_batches: 3
  limit_val_batches: 9
  # limit_val_batches: 3
  accelerator: "gpu"
  precision: 32
  devices: [0]
  # devices: [3]
  resume: null
  resume_from_checkpoint: null

# Augmentation configuration (Actually not used)
augmentation:
  wave:
    enable: False
    p_apply: 0.5
    rx_prob: 0.3
    rx_gain_db: [-20.0, 0.0]
    ps_prob: 0.3
    ps_semitones: [-3, 3]
    st_prob: 0.3
    st_beta: [1.0, 5.0]
    polarity_prob: 0.1

dev: false 